seeder:
  file: ./seeder/seeder.rb
exporters:
  - file: ./exporters/from_seeder_json.yaml
input_vars:
 - name: start_var1
   type: text
   required: true
 - name: start_with_env_var2
   type: text
   required: true
 - name: start_with_global_env_var3
   type: text
   required: true
 - name: start_with_env_var4
   type: text
   required: true
 - name: start_with_default_var5
   default: 'var5 value'
   required: true
 - name: start_optional_var6
env_vars:
 - name: start_with_env_var2
 - name: start_with_global_env_var3
   global_name: env_var3
 - name: start_with_env_var4
   default: "var4 value"
 - name: my_env1
   default: "my_env1 value"
 - name: my_required_env2
